# Generated by Django 5.0.3 on 2024-04-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xsauth', '0002_alter_capthamodel_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capthamodel',
            old_name='captha',
            new_name='captcha',
        ),
    ]
